Traceback (most recent call last):
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/run.py", line 87, in <module>
    schema.send("SET")
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/run.py", line 35, in __iter__
    yield self.__labor(class_=pipe)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/run.py", line 56, in __labor
    idx = next(xiter_class)  # CHAMANDO `__next__` de `class_`
          ^^^^^^^^^^^^^^^^^
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/__init__.py", line 53, in __next__
    self()
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/__init__.py", line 60, in __call__
    pipe_like = iter(PipeInstaLike(driver=self.driver, path=self.data.path))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/italo/Documentos/more/work_flow/services/instabot/services/app/pipes/pipe_like.py", line 19, in __iter__
    self.__io = open(self.path, "r+")
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'services/app/data.json'
